# Security scanning workflow
# Author: Kkasuga904
# Description: Automated security checks for dependencies and Docker images

name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security scan weekly on Monday
    - cron: '0 0 * * 1'

jobs:
  # ===========================
  # Python Security Scan
  # ===========================
  python-security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety bandit
    
    - name: Run Safety check (Known security vulnerabilities)
      run: safety check --json
      continue-on-error: true
    
    - name: Run Bandit (Security linter)
      run: bandit -r app/ -f json -o bandit-report.json
      continue-on-error: true

  # ===========================
  # Docker Security Scan
  # ===========================
  docker-security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'

  # ===========================
  # Dependency Check
  # ===========================
  dependency-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install and run pip-audit
      run: |
        python -m pip install --upgrade pip
        pip install pip-audit
        pip-audit --desc
      continue-on-error: true

  # ===========================
  # SAST (Static Application Security Testing)
  # ===========================
  sast:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: python
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2